# Test ci

name: Version Patch and Deploy

on:
  push:
    branches:
      - "ci-*"

jobs:
  version-patch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run npm version patch
        run: npm version patch

      - name: Configure Git for CI
        run: |
          git config user.name "TeamVisioneer"
          git config user.email "team.visioneer15@gmail.com"

      - name: Push version bump to main branch
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.PERSONAL_GITHUB_ADMIN_TOKEN }}@github.com/${{ github.repository }}
          git push origin HEAD:main
