name: Version Patch and Deploy

on:
  push:
    branches:
      - ci-trigger

jobs:
  version-patch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure Git for CI
        run: |
          git config user.name "TeamVisioneer"
          git config user.email "team.visioneer15@gmail.com"
          git clone https://x-access-token:${{ secrets.PERSONAL_GITHUB_ADMIN_TOKEN }}@github.com/${{ github.repository }} ${{ github.repository }}

      - name: version patch
        run: |
          cd ${{ github.repository }}
          npm version patch
          git push origin HEAD:main
